version: '2'

services:
  theano-deep-learning:
    image: theano-deep-learning:debug
    build:
      context: .
      dockerfile: Dockerfile.debug
    ports:
      - "3000:3000"
    volumes:
      - .:/src
    environment:
      - REMOTE_DEBUGGING
